{% set name = "dsm2dtm" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

# source:
#   git_url: https://github.com/seedlit/{{ name }}.git
source:
  # Relative path to the parent directory.
  # ref: https://stackoverflow.com/a/61810510
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  build:
    - git
    - python
    - pip
    - setuptools
  host:
    - pip
    - python
  run:
    - python
    - gdal >=3.0.*
    - rasterio >=1.2.*
    - numpy >=1.20.*

test:
  imports:
    - dsm2dtm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/seedlit/dsm2dtm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generates DTM (Digital Terrain Model) from DSM (Digital Surface Model).
  description: |
    Generates DTM (Digital Terrain Model) from DSM (Digital Surface Model).
  doc_url: https://github.com/seedlit/dsm2dtm#readme
  dev_url: https://github.com/seedlit/dsm2dtm
extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - seedlit